# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QMainWindow
from setting import *
import Mainwindow


class Ui_MainWindow(QMainWindow):
    signal = pyqtSignal(str)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(680, 450)
        MainWindow.setMinimumSize(QtCore.QSize(680, 450))
        MainWindow.setMaximumSize(QtCore.QSize(680, 463))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Cred1 = QtWidgets.QLineEdit(self.widget)
        self.Cred1.setMinimumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Cred1.setFont(font)
        self.Cred1.setObjectName("Cred1")
        self.verticalLayout.addWidget(self.Cred1)
        self.Cred2 = QtWidgets.QLineEdit(self.widget)
        self.Cred2.setMinimumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Cred2.setFont(font)
        self.Cred2.setObjectName("Cred2")
        self.verticalLayout.addWidget(self.Cred2)
        self.Cred3 = QtWidgets.QLineEdit(self.widget)
        self.Cred3.setMinimumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Cred3.setFont(font)
        self.Cred3.setObjectName("Cred3")
        self.verticalLayout.addWidget(self.Cred3)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.Protect1 = QtWidgets.QLineEdit(self.widget_2)
        self.Protect1.setMinimumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Protect1.setFont(font)
        self.Protect1.setObjectName("Protect1")
        self.verticalLayout_4.addWidget(self.Protect1)
        self.Protect2 = QtWidgets.QLineEdit(self.widget_2)
        self.Protect2.setMinimumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Protect2.setFont(font)
        self.Protect2.setObjectName("Protect2")
        self.verticalLayout_4.addWidget(self.Protect2)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.password = QtWidgets.QLineEdit(self.widget_3)
        self.password.setMinimumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.verticalLayout_2.addWidget(self.password)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.widget_4)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.cancel = QtWidgets.QPushButton(self.widget_4)
        self.cancel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel.setFont(font)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.apply = QtWidgets.QPushButton(self.widget_4)
        self.apply.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.apply.setFont(font)
        self.apply.setObjectName("apply")
        self.horizontalLayout.addWidget(self.apply)
        self.verticalLayout_3.addWidget(self.widget_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # =====================================
        self.Init()
        self.InitSignals()
        # =====================================
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Credentials Decryption Options"))
        self.label.setText(_translate("MainWindow", "Windows Credentials Folders"))
        self.label_2.setText(_translate("MainWindow", "Protect folders"))
        self.label_3.setText(_translate("MainWindow", "Windows Login Password:"))
        self.password.setPlaceholderText(_translate("MainWindow", "logon password"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
        self.apply.setText(_translate("MainWindow", "Apply"))

    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)

    def Init(self):
        cred_path = Load('cred_path')
        if cred_path and len(cred_path) >= 1:
            self.Cred1.setText(cred_path[0])
        if cred_path and len(cred_path) >= 2:
            self.Cred2.setText(cred_path[1])
        if cred_path and len(cred_path) >= 3:
            self.Cred3.setText(cred_path[2])

        sid_path = Load('sid_path')
        if sid_path and len(sid_path) >= 1:
            self.Protect1.setText(sid_path[0])
        if sid_path and len(sid_path) >= 2:
            self.Protect2.setText(sid_path[1])
        return

    def InitSignals(self):
        self.pushButton.clicked.connect(self.PressOK)
        self.cancel.clicked.connect(self.PressCanccel)
        self.apply.clicked.connect(self.PressApply)

    def PressOK(self):
        if self.PressApply():
            self.signal.emit(self.password.text())
        self.close()

    def PressCanccel(self):
        self.close()

    def PressApply(self):
        if self.password.text() != '':
            return True
        else:
            return False

